### ISSUE TITLE
EventWaiter not verifying reactions correctly

### ISSUE THREAD

**Issue by 0xCold** [droopytt/Malt-Aster-Bot#1]
The EventWaiter, specifically in UnoCommand, can accurately wait for the commander to react to a message and then perform an action, but cannot verify the emoji used when reacting. Could be a unicode issue

**Comment by droopytt** [comment]
This was indeed a unicode issue, but it has been resolved now anyway. The system has now been refactored to handle reactions, guild messages and private messages independently for each [Activity](https://github.com/droopytt/Malt-Aster-Bot/blob/master/src/main/java/com/malt/aster/activities/ActivityPhase.java) there is, and for each of the phases of the Activity.
